# Generated by Django 6.0.4 on 2026-05-28 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FootprintCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_input', models.JSONField()),
                ('total_footprint', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sustanibility_score', models.IntegerField()),
                ('food_footprint', models.FloatField()),
                ('transportation_footprint', models.FloatField()),
                ('energy_footprint', models.FloatField()),
                ('shopping_footprint', models.FloatField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
