# Generated by Django 6.0.4 on 2026-05-28 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footprintcalculation',
            old_name='sustanibility_score',
            new_name='sustainability',
        ),
        migrations.RenameField(
            model_name='footprintcalculation',
            old_name='total_footprint',
            new_name='totalfootprint',
        ),
    ]
