# Generated by Django 6.0.5 on 2026-05-30 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_sustanibility_score_footprintcalculation_sustainability_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footprintcalculation',
            old_name='sustainability',
            new_name='sustanibility_score',
        ),
        migrations.RenameField(
            model_name='footprintcalculation',
            old_name='totalfootprint',
            new_name='total_footprint',
        ),
    ]
