
export const COUNTRIES = [
  { code: "AF", name: "Afghanistan", capital: "Kabul" },
  { code: "AL", name: "Albania", capital: "Tirana" },
  { code: "DZ", name: "Algeria", capital: "Algiers" },
  { code: "AD", name: "Andorra", capital: "Andorra la Vella" },
  { code: "AO", name: "Angola", capital: "Luanda" },
  { code: "AG", name: "Antigua and Barbuda", capital: "Saint John's" },
  { code: "AR", name: "Argentina", capital: "Buenos Aires" },
  { code: "AM", name: "Armenia", capital: "Yerevan" },
  { code: "AU", name: "Australia", capital: "Canberra" },
  { code: "AT", name: "Austria", capital: "Vienna" },
  { code: "AZ", name: "Azerbaijan", capital: "Baku" },
  { code: "BS", name: "Bahamas", capital: "Nassau" },
  { code: "BH", name: "Bahrain", capital: "Manama" },
  { code: "BD", name: "Bangladesh", capital: "Dhaka" },
  { code: "BB", name: "Barbados", capital: "Bridgetown" },
  { code: "BY", name: "Belarus", capital: "Minsk" },
  { code: "BE", name: "Belgium", capital: "Brussels" },
  { code: "BZ", name: "Belize", capital: "Belmopan" },
  { code: "BJ", name: "Benin", capital: "Porto-Novo" },
  { code: "BT", name: "Bhutan", capital: "Thimphu" },
  { code: "BO", name: "Bolivia", capital: "Sucre" },
  { code: "BA", name: "Bosnia and Herzegovina", capital: "Sarajevo" },
  { code: "BW", name: "Botswana", capital: "Gaborone" },
  { code: "BR", name: "Brazil", capital: "Brasília" },
  { code: "BN", name: "Brunei", capital: "Bandar Seri Begawan" },
  { code: "BG", name: "Bulgaria", capital: "Sofia" },
  { code: "BF", name: "Burkina Faso", capital: "Ouagadougou" },
  { code: "BI", name: "Burundi", capital: "Gitega" },
  { code: "CV", name: "Cabo Verde", capital: "Praia" },
  { code: "KH", name: "Cambodia", capital: "Phnom Penh" },
  { code: "CM", name: "Cameroon", capital: "Yaoundé" },
  { code: "CA", name: "Canada", capital: "Ottawa" },
  { code: "CF", name: "Central African Republic", capital: "Bangui" },
  { code: "TD", name: "Chad", capital: "N'Djamena" },
  { code: "CL", name: "Chile", capital: "Santiago" },
  { code: "CN", name: "China", capital: "Beijing" },
  { code: "CO", name: "Colombia", capital: "Bogotá" },
  { code: "KM", name: "Comoros", capital: "Moroni" },
  { code: "CG", name: "Congo (Republic of the)", capital: "Brazzaville" },
  { code: "CD", name: "Congo (DR)", capital: "Kinshasa" },
  { code: "CR", name: "Costa Rica", capital: "San José" },
  { code: "CI", name: "Côte d'Ivoire", capital: "Yamoussoukro" },
  { code: "HR", name: "Croatia", capital: "Zagreb" },
  { code: "CU", name: "Cuba", capital: "Havana" },
  { code: "CY", name: "Cyprus", capital: "Nicosia" },
  { code: "CZ", name: "Czechia", capital: "Prague" },
  { code: "DK", name: "Denmark", capital: "Copenhagen" },
  { code: "DJ", name: "Djibouti", capital: "Djibouti" },
  { code: "DM", name: "Dominica", capital: "Roseau" },
  { code: "DO", name: "Dominican Republic", capital: "Santo Domingo" },
  { code: "EC", name: "Ecuador", capital: "Quito" },
  { code: "EG", name: "Egypt", capital: "Cairo" },
  { code: "SV", name: "El Salvador", capital: "San Salvador" },
  { code: "GQ", name: "Equatorial Guinea", capital: "Malabo" },
  { code: "ER", name: "Eritrea", capital: "Asmara" },
  { code: "EE", name: "Estonia", capital: "Tallinn" },
  { code: "SZ", name: "Eswatini", capital: "Mbabane" },
  { code: "ET", name: "Ethiopia", capital: "Addis Ababa" },
  { code: "FJ", name: "Fiji", capital: "Suva" },
  { code: "FI", name: "Finland", capital: "Helsinki" },
  { code: "FR", name: "France", capital: "Paris" },
  { code: "GA", name: "Gabon", capital: "Libreville" },
  { code: "GM", name: "Gambia", capital: "Banjul" },
  { code: "GE", name: "Georgia", capital: "Tbilisi" },
  { code: "DE", name: "Germany", capital: "Berlin" },
  { code: "GH", name: "Ghana", capital: "Accra" },
  { code: "GR", name: "Greece", capital: "Athens" },
  { code: "GD", name: "Grenada", capital: "Saint George's" },
  { code: "GT", name: "Guatemala", capital: "Guatemala City" },
  { code: "GN", name: "Guinea", capital: "Conakry" },
  { code: "GW", name: "Guinea-Bissau", capital: "Bissau" },
  { code: "GY", name: "Guyana", capital: "Georgetown" },
  { code: "HT", name: "Haiti", capital: "Port-au-Prince" },
  { code: "HN", name: "Honduras", capital: "Tegucigalpa" },
  { code: "HU", name: "Hungary", capital: "Budapest" },
  { code: "IS", name: "Iceland", capital: "Reykjavík" },
  { code: "IN", name: "India", capital: "New Delhi" },
  { code: "ID", name: "Indonesia", capital: "Jakarta" },
  { code: "IR", name: "Iran", capital: "Tehran" },
  { code: "IQ", name: "Iraq", capital: "Baghdad" },
  { code: "IE", name: "Ireland", capital: "Dublin" },
  { code: "IL", name: "Israel", capital: "Jerusalem" },
  { code: "IT", name: "Italy", capital: "Rome" },
  { code: "JM", name: "Jamaica", capital: "Kingston" },
  { code: "JP", name: "Japan", capital: "Tokyo" },
  { code: "JO", name: "Jordan", capital: "Amman" },
  { code: "KZ", name: "Kazakhstan", capital: "Astana" },
  { code: "KE", name: "Kenya", capital: "Nairobi" },
  { code: "KI", name: "Kiribati", capital: "South Tarawa" },
  { code: "KP", name: "Korea (North)", capital: "Pyongyang" },
  { code: "KR", name: "Korea (South)", capital: "Seoul" },
  { code: "KW", name: "Kuwait", capital: "Kuwait City" },
  { code: "KG", name: "Kyrgyzstan", capital: "Bishkek" },
  { code: "LA", name: "Laos", capital: "Vientiane" },
  { code: "LV", name: "Latvia", capital: "Riga" },
  { code: "LB", name: "Lebanon", capital: "Beirut" },
  { code: "LS", name: "Lesotho", capital: "Maseru" },
  { code: "LR", name: "Liberia", capital: "Monrovia" },
  { code: "LY", name: "Libya", capital: "Tripoli" },
  { code: "LI", name: "Liechtenstein", capital: "Vaduz" },
  { code: "LT", name: "Lithuania", capital: "Vilnius" },
  { code: "LU", name: "Luxembourg", capital: "Luxembourg" },
  { code: "MG", name: "Madagascar", capital: "Antananarivo" },
  { code: "MW", name: "Malawi", capital: "Lilongwe" },
  { code: "MY", name: "Malaysia", capital: "Kuala Lumpur" },
  { code: "MV", name: "Maldives", capital: "Malé" },
  { code: "ML", name: "Mali", capital: "Bamako" },
  { code: "MT", name: "Malta", capital: "Valletta" },
  { code: "MH", name: "Marshall Islands", capital: "Majuro" },
  { code: "MR", name: "Mauritania", capital: "Nouakchott" },
  { code: "MU", name: "Mauritius", capital: "Port Louis" },
  { code: "MX", name: "Mexico", capital: "Mexico City" },
  { code: "FM", name: "Micronesia", capital: "Palikir" },
  { code: "MD", name: "Moldova", capital: "Chișinău" },
  { code: "MC", name: "Monaco", capital: "Monaco" },
  { code: "MN", name: "Mongolia", capital: "Ulaanbaatar" },
  { code: "ME", name: "Montenegro", capital: "Podgorica" },
  { code: "MA", name: "Morocco", capital: "Rabat" },
  { code: "MZ", name: "Mozambique", capital: "Maputo" },
  { code: "MM", name: "Myanmar", capital: "Naypyidaw" },
  { code: "NA", name: "Namibia", capital: "Windhoek" },
  { code: "NR", name: "Nauru", capital: "Yaren" },
  { code: "NP", name: "Nepal", capital: "Kathmandu" },
  { code: "NL", name: "Netherlands", capital: "Amsterdam" },
  { code: "NZ", name: "New Zealand", capital: "Wellington" },
  { code: "NI", name: "Nicaragua", capital: "Managua" },
  { code: "NE", name: "Niger", capital: "Niamey" },
  { code: "NG", name: "Nigeria", capital: "Abuja" },
  { code: "MK", name: "North Macedonia", capital: "Skopje" },
  { code: "NO", name: "Norway", capital: "Oslo" },
  { code: "OM", name: "Oman", capital: "Muscat" },
  { code: "PK", name: "Pakistan", capital: "Islamabad" },
  { code: "PW", name: "Palau", capital: "Ngerulmud" },
  { code: "PA", name: "Panama", capital: "Panama City" },
  { code: "PG", name: "Papua New Guinea", capital: "Port Moresby" },
  { code: "PY", name: "Paraguay", capital: "Asunción" },
  { code: "PE", name: "Peru", capital: "Lima" },
  { code: "PH", name: "Philippines", capital: "Manila" },
  { code: "PL", name: "Poland", capital: "Warsaw" },
  { code: "PT", name: "Portugal", capital: "Lisbon" },
  { code: "QA", name: "Qatar", capital: "Doha" },
  { code: "RO", name: "Romania", capital: "Bucharest" },
  { code: "RU", name: "Russia", capital: "Moscow" },
  { code: "RW", name: "Rwanda", capital: "Kigali" },
  { code: "KN", name: "Saint Kitts and Nevis", capital: "Basseterre" },
  { code: "LC", name: "Saint Lucia", capital: "Castries" },
  { code: "VC", name: "Saint Vincent and the Grenadines", capital: "Kingstown" },
  { code: "WS", name: "Samoa", capital: "Apia" },
  { code: "SM", name: "San Marino", capital: "San Marino" },
  { code: "ST", name: "São Tomé and Príncipe", capital: "São Tomé" },
  { code: "SA", name: "Saudi Arabia", capital: "Riyadh" },
  { code: "SN", name: "Senegal", capital: "Dakar" },
  { code: "RS", name: "Serbia", capital: "Belgrade" },
  { code: "SC", name: "Seychelles", capital: "Victoria" },
  { code: "SL", name: "Sierra Leone", capital: "Freetown" },
  { code: "SG", name: "Singapore", capital: "Singapore" },
  { code: "SK", name: "Slovakia", capital: "Bratislava" },
  { code: "SI", name: "Slovenia", capital: "Ljubljana" },
  { code: "SB", name: "Solomon Islands", capital: "Honiara" },
  { code: "SO", name: "Somalia", capital: "Mogadishu" },
  { code: "ZA", name: "South Africa", capital: "Pretoria" },
  { code: "SS", name: "South Sudan", capital: "Juba" },
  { code: "ES", name: "Spain", capital: "Madrid" },
  { code: "LK", name: "Sri Lanka", capital: "Sri Jayawardenepura Kotte" },
  { code: "SD", name: "Sudan", capital: "Khartoum" },
  { code: "SR", name: "Suriname", capital: "Paramaribo" },
  { code: "SE", name: "Sweden", capital: "Stockholm" },
  { code: "CH", name: "Switzerland", capital: "Bern" },
  { code: "SY", name: "Syria", capital: "Damascus" },
  { code: "TW", name: "Taiwan", capital: "Taipei" },
  { code: "TJ", name: "Tajikistan", capital: "Dushanbe" },
  { code: "TZ", name: "Tanzania", capital: "Dodoma" },
  { code: "TH", name: "Thailand", capital: "Bangkok" },
  { code: "TL", name: "Timor-Leste", capital: "Dili" },
  { code: "TG", name: "Togo", capital: "Lomé" },
  { code: "TO", name: "Tonga", capital: "Nuku'alofa" },
  { code: "TT", name: "Trinidad and Tobago", capital: "Port of Spain" },
  { code: "TN", name: "Tunisia", capital: "Tunis" },
  { code: "TR", name: "Turkey", capital: "Ankara" },
  { code: "TM", name: "Turkmenistan", capital: "Ashgabat" },
  { code: "TV", name: "Tuvalu", capital: "Funafuti" },
  { code: "UG", name: "Uganda", capital: "Kampala" },
  { code: "UA", name: "Ukraine", capital: "Kyiv" },
  { code: "AE", name: "United Arab Emirates", capital: "Abu Dhabi" },
  { code: "GB", name: "United Kingdom", capital: "London" },
  { code: "US", name: "United States", capital: "Washington, D.C." },
  { code: "UY", name: "Uruguay", capital: "Montevideo" },
  { code: "UZ", name: "Uzbekistan", capital: "Tashkent" },
  { code: "VU", name: "Vanuatu", capital: "Port Vila" },
  { code: "VA", name: "Vatican City", capital: "Vatican City" },
  { code: "VE", name: "Venezuela", capital: "Caracas" },
  { code: "VN", name: "Vietnam", capital: "Hanoi" },
  { code: "YE", name: "Yemen", capital: "Sana'a" },
  { code: "ZM", name: "Zambia", capital: "Lusaka" },
  { code: "ZW", name: "Zimbabwe", capital: "Harare" },
];

export function capitalOf(code) {
  return COUNTRIES.find((c) => c.code === code)?.capital ?? "";
}