# Generated by Django 6.0.4 on 2026-07-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='total_footprint',
            field=models.FloatField(default=0.0),
        ),
    ]
