# Generated by Django 6.0.4 on 2026-07-23 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_total_footprint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='company',
            name='usage',
        ),
    ]
