# Generated by Django 6.0.5 on 2026-07-24 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_contactmessage_userrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_otps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
